<?php
$locations = array(
  'New York City',
  'Los Angeles',
  'Chicago',
  'Houston',
  'Philadelphia',
  'Phoenix',
  'San Diego',
  'Dallas',
  'San Antonio',
  'Detroit',
  'San Jose',
  'Indianapolis',
  'San Francisco',
  'Jacksonville',
  'Columbus',
  'Austin',
  'Memphis',
  'Baltimore',
  'Milwaukee',
  'Boston',
  'Charlotte',
  'El Paso',
  'Washington',
  'Nashville-Davidson',
  'Seattle',
  'Fort Worth',
  'Denver',
  'Portland',
  'Oklahoma',
  'Las Vegas',
  'Tucson',
  'New Orleans',
  'Long Beach',
  'Cleveland',
  'Albuquerque',
  'Fresno',
  'Kansas',
  'Sacramento',
  'Virginia Beach',
  'Mesa',
  'Atlanta',
  'Oakland',
  'Omaha',
  'Tulsa',
  'Honolulu CDP',
  'Minneapolis',
  'Miami',
  'Colorado Springs',
  'Wichita',
  'Arlington',
  'Santa Ana',
  'St. Louis',
  'Anaheim',
  'Pittsburgh',
  'Cincinnati',
  'Tampa',
  'Toledo',
  'Raleigh',
  'Buffalo',
  'Aurora',
  'St. Paul',
  'Corpus Christi',
  'Newark',
  'Riverside',
  'Anchorage',
  'Lexington-Fayette',
  'Stockton',
  'Bakersfield',
  'Louisville',
  'St. Petersburg',
  'Jersey',
  'Birmingham',
  'Norfolk',
  'Plano',
  'Lincoln',
  'Glendale',
  'Greensboro',
  'Hialeah',
  'Baton Rouge',
  'Garland',
  'Rochester',
  'Scottsdale',
  'Madison',
  'Akron',
  'Fort Wayne',
  'Fremont',
  'Chesapeake',
  'Henderson',
  'Lubbock',
  'Modesto',
  'Chandler',
  'Montgomery',
  'Glendale',
  'Shreveport',
  'Des Moines',
  'Augusta-Richmond',
  'Tacoma',
  'Richmond',
  'Yonkers',
  'Grand Rapids',
  'Spokane',
  'Irving',
  'Durham',
  'Mobile',
  'Chula Vista',
  'Huntington Beach',
  'Orlando',
  'San Bernardino',
  'Laredo',
  'Reno',
  'Arlington CDP',
  'Boise',
  'Winston-Salem',
  'Columbus',
  'Little Rock',
  'Salt Lake',
  'Jackson',
  'Newport News',
  'Oxnard',
  'Amarillo',
  'Providence',
  'Worcester',
  'Knoxville',
  'Garden Grove',
  'Oceanside',
  'Ontario',
  'Dayton',
  'Huntsville',
  'Irvine',
  'Santa Clarita',
  'Tempe',
  'Overland Park',
  'Fort Lauderdale',
  'Aurora',
  'Chattanooga',
  'Tallahassee',
  'Pomona',
  'Santa Rosa',
  'Springfield',
  'Rockford',
  'Springfield',
  'Moreno Valley',
  'Paterson',
  'Brownsville',
  'Vancouver',
  'Salinas',
  'Kansas',
  'Pembroke Pines',
  'Hampton',
  'Syracuse',
  'Pasadena',
  'Lakewood',
  'Rancho Cucamonga',
  'Fontana',
  'Hollywood',
  'Hayward',
  'Torrance',
  'Salem',
  'Eugene',
  'Bridgeport',
  'Pasadena',
  'Corona',
  'Warren',
  'Escondido',
  'North Las Vegas',
  'Naperville',
  'Grand Prairie',
  'Gilbert town',
  'Orange',
  'Alexandria',
  'Sioux Falls',
  'Sunnyvale',
  'Fullerton',
  'Mesquite',
  'Savannah',
  'Sterling Heights',
  'Coral Springs',
  'Concord',
  'Fort Collins',
  'Lancaster',
  'Hartford',
  'Palmdale',
  'Fayetteville',
  'New Haven',
  'Elizabeth',
  'Peoria',
  'Thousand Oaks',
  'Cedar Rapids',
  'Topeka',
  'Flint',
  'El Monte',
  'Stamford',
  'Vallejo',
  'Evansville',
  'Lansing',
  'Joliet',
  'Columbia',
  'Simi Valley',
  'Waco',
  'Abilene',
  'Ann Arbor',
  'Carrollton',
  'Inglewood',
  'McAllen',
  'Independence',
  'Cape Coral',
  'Bellevue',
  'Beaumont',
  'Peoria',
  'Springfield',
  'Lafayette',
  'West Valley',
  'Costa Mesa',
  'Downey',
  'Manchester',
  'Clearwater',
  'Waterbury',
  'West Covina',
  'South Bend',
  'Allentown',
  'Norwalk',
  'Clarksville',
  'Provo',
  'Lowell',
  'Athens-Clarke County',
  'Berkeley',
  'Ventura',
  'Westminster',
  'Pueblo',
  'Wichita Falls',
  'Burbank',
  'Richmond',
  'Arvada',
  'Erie',
  'Fairfield',
  'Daly',
  'Santa Clara',
  'Cambridge',
  'Green Bay',
  'Olathe',
  'Gary',
  'Livonia',
  'Antioch',
  'Portsmouth',
  'Centennial',
  'Charleston',
  'South Gate',
  'Port St. Lucie',
  'Cary town',
  'Dearborn',
  'Norman',
  'Davenport',
  'Everett',
  'Richardson',
  'Visalia',
  'Rialto',
  'Elgin',
  'Mission Viejo',
  'Macon',
  'Midland',
  'Compton',
  'El Cajon',
  'Brockton',
  'Gainesville',
  'Gresham',
  'Boulder',
  'New Bedford',
  'Roanoke',
  'Albany',
  'Thornton',
  'Vacaville',
  'Carson',
  'Killeen',
  'Fall River',
  'Kenosha',
  'Billings',
  'San Mateo',
  'Roseville',
  'Vista',
  'Lawton',
  'Waukegan',
  'Fargo',
  'Odessa',
  'Wilmington',
  'High Point',
  'Rochester',
  'Miramar',
  'Denton',
  'Lynn',
  'Miami Beach',
  'Westminster',
  'Santa Barbara',
  'Sandy',
  'Quincy',
  'Citrus Heights',
  'Sunrise',
  'Nashua',
  'Alhambra',
  'San Angelo',
  'Pompano Beach',
  'United States',
  'London',
  'Birmingham',
  'Leeds',
  'Glasgow',
  'Sheffield',
  'Bradford',
  'Edinburgh',
  'Liverpool',
  'Manchester',
  'Bristol',
  'Wakefield',
  'Cardiff',
  'Coventry',
  'Nottingham',
  'Leicester',
  'Sunderland',
  'Belfast',
  'Newcastle Upon Tyne',
  'Brighton',
  'Hull',
  'Plymouth',
  'Stoke-on-Trent',
  'Wolverhampton',
  'Derby',
  'Swansea',
  'Southampton',
  'Salford',
  'Aberdeen',
  'Westminster',
  'Portsmouth',
  'York',
  'Peterborough',
  'Dundee',
  'Lancaster',
  'Oxford',
  'Newport',
  'Preston',
  'Saint Albans',
  'Norwich',
  'Chester',
  'Cambridge',
  'Salisbury',
  'Exeter',
  'Gloucester',
  'Lisburn',
  'Chichester',
  'Winchester',
  'Londonderry',
  'Carlisle',
  'Worcester',
  'Bath',
  'Durham',
  'Lincoln',
  'Hereford',
  'Armagh',
  'Inverness',
  'Stirling',
  'Canterbury',
  'Lichfield',
  'Newry',
  'Ripon',
  'Bangor',
  'Truro',
  'Ely',
  'Wells',
  'St Davids',
  'United Kingdom',
  'Toronto',
  'Montreal',
  'Calgary',
  'Ottawa',
  'Edmonton',
  'Mississauga',
  'Winnipeg',
  'Vancouver',
  'Brampton',
  'Hamilton',
  'Quebec City',
  'Surrey',
  'Laval',
  'Halifax',
  'London',
  'Markham',
  'Vaughan',
  'Gatineau',
  'Longueuil',
  'Burnaby',
  'Saskatoon',
  'Kitchener',
  'Windsor',
  'Regina',
  'Richmond',
  'Richmond Hill',
  'Oakville',
  'Burlington',
  'Greater Sudbury',
  'Sherbrooke',
  'Oshawa',
  'Saguenay',
  'Levis',
  'Barrie',
  'Abbotsford',
  'St. Catharines',
  'Trois-Rivières',
  'Cambridge',
  'Coquitlam',
  'Kingston',
  'Whitby',
  'Guelph',
  'Kelowna',
  'Saanich',
  'Ajax',
  'Thunder Bay',
  'Terrebonne',
  'St. John\'s',
  'Langley',
  'Chatham-Kent',
  'Delta',
  'Waterloo',
  'Cape Breton',
  'Brantford',
  'Strathcona County',
  'Saint-Jean-sur-Richelieu',
  'Red Deer',
  'Pickering',
  'Kamloops',
  'Clarington',
  'North Vancouver',
  'Milton',
  'Nanaimo',
  'Lethbridge',
  'Niagara Falls',
  'Repentigny',
  'Victoria',
  'Newmarket',
  'Brossard',
  'Peterborough',
  'Chilliwack',
  'Maple Ridge',
  'Sault Sainte Marie',
  'Kawartha Lakes',
  'Sarnia',
  'Prince George',
  'Drummondville',
  'Saint John',
  'Moncton',
  'Saint-Jerome',
  'New Westminster',
  'Wood Buffalo',
  'Granby',
  'Norfolk County',
  'Saint Albert',
  'Medicine Hat',
  'Caledon',
  'Halton Hills',
  'Port Coquitlam',
  'Fredericton',
  'Grande Prairie',
  'North Bay',
  'Blainville',
  'Saint-Hyacinthe',
  'Aurora',
  'Welland',
  'Shawinigan',
  'Dollard-des-Ormeaux',
  'Belleville',
  'North Vancouver',
  'Canada',
  ''
);

